<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0OE0D1U" ignored="0" name="Test" tests="8" failures="2" timestamp="14 Apr 2021 11:52:37 GMT" time="0.111" errors="0">
  <testcase name="test1" time="0.019" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.003" classname="RetryTestng.retryConcept">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at RetryTestng.retryConcept.test1(retryConcept.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="RetryTestng.retryConcept">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="RetryTestng.retryConcept">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at RetryTestng.retryConcept.test2(retryConcept.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
